# version: '2'
# services:
#   db:
#     image: 'mongo:3.4-xenial'
#     restart: always
#     env_file:
#       - ./backend/.env
#   server:
#     build: ./backend/
#     restart: always
#     depends_on:
#       - db
#     links:
#       - 'db:db'
#     ports:
#       - '4000:3000'
#   client:
#     build: ./frontend/
#     depends_on:
#       - server
#     links:
#       - 'server:server'
#     ports:
#       - '4002:4200'